backend:
    build: ./utils/docker/backend
    links:
        - db
    ports:
        - "${BACKEND_PORT}:80"
        - "443:443"
    volumes:
        - ./backend:/var/www/html
frontend:
    image: httpd
    links:
        - backend
    ports:
        - "${FRONTEND_PORT}:80"
    volumes:
        - ./frontend/build:/usr/local/apache2/htdocs
db:
    build: ./utils/docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
        - "${MYSQL_PORT}:3306"