backend:
    build: ./utils/docker/backend
    links:
        - db
    ports:
        - "${BACKEND_PORT}:80"
        - "${BACKEND_SSL_PORT}:443"
    volumes:
        - ./backend:/var/www/html
website:
    image: nginx
    links:
        - backend
    ports:
        - "${FRONTEND_PORT}:80"
    environment: 
        DRUPAL_USER: ${DRUPAL_USER}
        DRUPAL_PASSWD: ${DRUPAL_PASSWD}
        API_URL: "http://${SERVER_NAME}:${BACKEND_PORT}"
    volumes:
        - ./website/out:/usr/share/nginx/html
        - ./utils/docker/website/default.conf:/etc/nginx/conf.d/default.conf
db:
    build: ./utils/docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
        - "${MYSQL_PORT}:3306"