backend:
    build: apache-drupal
    links:
        - db
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./backend:/var/www/html
frontend:
    build: apache
    links:
        - backend
    ports:
        - "8080:80"
    volumes:
        - ./frontend/build:/usr/local/apache2/htdocs
db:
    build: mysql
    ports:
        - "3306:3306"